/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include"main.h"
#include "HAL/TFT/TFT_Lcfg.h"
#include "my_pic.h"

// ----------------------------------------------------------------------------
u32 counter;

int main(void)
{

	TFT_voidInit(&TFT_Config);


	while(1)
	{

		TFT_WriteStringPosWithBgColor(&TFT_Config,0,0,"HELLO IMT",TFT_BLUE,TFT_WHITE);
		Delay_sec(5);
		TFT_WriteStringPosWithBgColor(&TFT_Config,1,0,"TFT Driver",TFT_RED,TFT_WHITE);
		Delay_sec(5);
		TFT_WriteStringPosWithBgColor(&TFT_Config,4,0,"Completed",TFT_GREEN,TFT_WHITE);
		Delay_sec(5);
		TFT_ClearScreen(&TFT_Config);
		//TFT_WriteCharPosWithBgColor(&TFT_Config, 0,0,'M', BLUE, BLACK);
	}

}
